language: elixir
elixir:
  - 1.2.3
  - 1.3.4
  - 1.4.0
  - 1.5.0
sudo: false
notifications:
  recipients:
    - self@falood.me
before_script:
  - mix deps.get --only test
script:
  - mix coveralls.travis
env:
  - MIX_ENV=test
